/**
 * lib/firebase.ts
 *
 * Initialises the Firebase SDK for the VORTREXYN Hangman app.
 *
 * Why a single file for this?
 * Firebase must only be initialised once per JS runtime.  Exporting `auth`
 * and `db` from here gives every module a shared, singleton reference to the
 * same Firebase services without risking double-initialisation errors.
 *
 * Auth persistence strategy:
 *  - Native (iOS / Android): `getReactNativePersistence(AsyncStorage)` — saves
 *    the logged-in session to the device's AsyncStorage so users stay signed in
 *    after closing the app.
 *  - Web: `browserLocalPersistence` — saves the session in localStorage.
 *    A try/catch wraps the call because `initializeAuth` throws if it has
 *    already been called for this app instance (e.g. hot-reload in dev).
 */

import { initializeApp, getApps } from "firebase/app";
import {
  initializeAuth,
  getAuth,
  getReactNativePersistence,
  browserLocalPersistence,
} from "firebase/auth";
import { getFirestore } from "firebase/firestore";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { Platform } from "react-native";

/** Firebase project configuration — generated by the Firebase console. */
const firebaseConfig = {
  apiKey: "AIzaSyDz2X0QlhyRxLRtDxPTUNYf40jyyvYXAXM",
  authDomain: "vortrexyn-hangman.firebaseapp.com",
  projectId: "vortrexyn-hangman",
  storageBucket: "vortrexyn-hangman.firebasestorage.app",
  messagingSenderId: "610164475078",
  appId: "1:610164475078:web:08ac37708bdb8f539a03c7",
  measurementId: "G-2BDWCLJS9V",
};

/**
 * Initialise the Firebase app exactly once.
 * `getApps()` returns an array of already-initialised apps, so if the array
 * is non-empty we reuse the existing instance (important during hot-reload).
 */
const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApps()[0];

/**
 * `auth` — Firebase Authentication instance.
 *
 * Platform-aware initialisation:
 *  - Web  → `browserLocalPersistence` keeps the user logged in via localStorage.
 *  - Native → `getReactNativePersistence(AsyncStorage)` persists the session
 *             across app restarts using React Native's AsyncStorage.
 */
export const auth =
  Platform.OS === "web"
    ? (() => {
        try {
          // Try to create a new auth instance with browser-local persistence.
          return initializeAuth(app, { persistence: browserLocalPersistence });
        } catch {
          // If initializeAuth already ran (hot-reload), fall back to getAuth.
          return getAuth(app);
        }
      })()
    : initializeAuth(app, {
        // On native devices, persist the auth token in AsyncStorage
        // so users stay signed in after force-quitting the app.
        persistence: getReactNativePersistence(AsyncStorage),
      });

/**
 * `db` — Firestore database instance.
 * Used across the app to read and write user profiles and game statistics.
 */
export const db = getFirestore(app);
